spring:
  application:
    name: user-service
server:
  port: 8087

eureka:         
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: false
